CREATE EXTENSION IF NOT EXISTS vector;

CREATE TABLE knowledge_documents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL UNIQUE REFERENCES tickets (id) ON DELETE CASCADE,
    content_hash VARCHAR(64) NOT NULL,
    snapshot_status VARCHAR(32) NOT NULL,
    snapshot_priority VARCHAR(32) NOT NULL,
    snapshot_assignee VARCHAR(120),
    snapshot_category VARCHAR(64) NOT NULL,
    canonical_text TEXT NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL
);

CREATE TABLE ingestion_records (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT NOT NULL UNIQUE REFERENCES tickets (id) ON DELETE CASCADE,
    status VARCHAR(32) NOT NULL,
    indexed_content_hash VARCHAR(64),
    last_attempt_at TIMESTAMP(6) WITH TIME ZONE,
    last_success_at TIMESTAMP(6) WITH TIME ZONE,
    failure_reason VARCHAR(200)
);

CREATE TABLE chunk_records (
    id UUID PRIMARY KEY,
    ticket_id BIGINT NOT NULL REFERENCES tickets (id) ON DELETE CASCADE,
    document_id BIGINT NOT NULL REFERENCES knowledge_documents (id) ON DELETE CASCADE,
    ordinal INT NOT NULL,
    chunk_text TEXT NOT NULL,
    ticket_id_meta BIGINT NOT NULL,
    status VARCHAR(32) NOT NULL,
    priority VARCHAR(32) NOT NULL,
    assignee VARCHAR(120),
    category VARCHAR(64) NOT NULL,
    embedding vector(32) NOT NULL,
    CONSTRAINT chunk_records_ticket_meta_matches CHECK (ticket_id_meta = ticket_id)
);

CREATE INDEX chunk_records_ticket_id_idx ON chunk_records (ticket_id);
